### ISSUE TITLE
Multi-PV support

### ISSUE THREAD

**Issue by tissatussa** [lynx-chess/Lynx#218]
lately i stumbled upon this position

`r1bq1rk1/pp4pp/2nbpn2/3p4/3P4/3B1N2/PP2NPPP/R1BQR1K1 b - - 0 12`

Black to play .. it seemed Ng4! was best, maybe continued by Nxf2!
Not all engines consider this move .. however, strong engines like SF and Berserk immediately find Ng4 best move and stick to that judgement .. i used Multi-PV 8 in SCID to see how a move like Ng4 can become clearly 'best move'.

--used engines and rating:
```
3500 Berserk_v10-NN
3100 Elektro_v2.0
3300 Marvin_v6.1.0-NNUE
3500 SF_v15-NNUE
3250 Stash_v33.23
```

pay attention to the Rodent-IV family, rating about 3000 : i used the personalities Larsen, Bosboom, Kasparov, Anderssen and Anand .. they all differ. 

Rodent has many parameters and thus many personalities are created .. the user can also tune these values in a config file .. i guess the pruning of the search is changed by those parameters, the move Ng4 might not appear in the top-8 list at all ..
I attached the personalities config file of Larsen for reference.

![Berserk_v10-NN-mpv8](https://user-images.githubusercontent.com/1109281/204041152-ea446bee-8575-4309-9760-c09690d655f2.png)

![Elektro_v2 0-mpv8](https://user-images.githubusercontent.com/1109281/204041178-4b951d8a-b2bd-4ed1-bc16-92de50b413da.png)

![Marvin_v6 1 0-NNUE-mpv8](https://user-images.githubusercontent.com/1109281/204041191-44d8ad39-92cc-479f-abdf-12255b66348a.png)

![SF_v15-NNUE-mpv8](https://user-images.githubusercontent.com/1109281/204041212-45b3fc4b-248b-4fb7-8dfd-faedf4b1c622.png)

![Stash_v33 23-mpv8](https://user-images.githubusercontent.com/1109281/204041228-f2f0b9fd-f514-40bc-a39d-a05c2dd4355c.png)

![Rodent-IV_Anderssen-mpv8](https://user-images.githubusercontent.com/1109281/204041263-3b2902be-9b0a-4675-a236-dc30777453ab.png)

![Rodent-IV_Anand-mpv8](https://user-images.githubusercontent.com/1109281/204041277-c9352c17-ceb5-460f-92db-0bae7333d26e.png)

![Rodent-IV_Bosboom-mpv8](https://user-images.githubusercontent.com/1109281/204041300-016cd2f8-3c8b-455a-bead-9fd4dd84580e.png)

![Rodent-IV_Kasparov-mpv8](https://user-images.githubusercontent.com/1109281/204041329-1195b866-3177-40e6-bb38-b595c4e6213e.png)

![Rodent-IV_Larsen-mpv8](https://user-images.githubusercontent.com/1109281/204041344-791685c0-47e4-4d55-8b5f-c32810503374.png)

```

; Personnalité "Larsen attaquant" pour Rodent IV
; Auteur : Rob Robinson
;
; PARAMETRES MATERIELS
;
setoption name PawnValueMg value 90
setoption name KnightValueMg value 380
setoption name BishopValueMg value 390
setoption name RookValueMg value 530
setoption name QueenValueMg value 1160
;
setoption name PawnValueEg value 110
setoption name KnightValueEg value 360
setoption name BishopValueEg value 370
setoption name RookValueEg value 650
setoption name QueenValueEg value 1190
;
; Keep (préférence)
;
setoption name KeepPawn value 0
setoption name KeepKnight value 5 ; +5
setoption name KeepBishop value 0
setoption name KeepRook value 5 ; +5
setoption name KeepQueen value 0
;
; Paires
;
setoption name BishopPairMg value 51
setoption name BishopPairEg value 51
setoption name KnightPair value 0 ; standard : -1
setoption name RookPair value -5 ; standard : -11
;
; Autres
;
setoption name ExchangeImbalance value 20
setoption name Material value 90 ; jeu peu matérialiste
setoption name KnightLikesClosed value 6 ; neutre
setoption name RookLikesOpen value 0 ; opening for towers
setoption name MinorVsQueen value 10
;
; PERSONALITY MATCH and STYLES
;
setoption name OwnAttack value 120; attacker...
setoption name OppAttack value 100; ...moderate
setoption name OwnMobility value 55; high mobility
setoption name OppMobility value 65; ... and blocking
setoption name FlatMobility value 45
;
setoption name PrimaryPstStyle value 1; style ''classic''
setoption name SecondaryPstStyle value 4; style ''forward''
setoption name PrimaryPstWeight value 70; increased primary
setoption name SecondaryPstWeight value 30; secondaire minoré
;
setoption name KingTropism value 25
setoption name PiecePressure value 150 ; standard + 50 (marqueur offensif)
setoption name Lines value 110 ; standard +10
setoption name Outposts value 100
setoption name Space value 20
;
; STRUCTURE DE PIONS
;
setoption name PawnStructure value 90 ; structure de pions plus faible
setoption name PassedPawns value 90 ; intérêt amoindri pour la promotion
setoption name PawnMass value 100
setoption name PawnChains value 100
setoption name PawnShield value 119
setoption name PawnStorm value 99
;
setoption name DoubledPawnMg value -2 ; standard : -8
setoption name DoubledPawnEg value -10 ; standard : -21
setoption name IsolatedPawnMg value -7
setoption name IsolatedPawnEg value -7
setoption name IsolatedOnOpenMg value -13
setoption name BackwardPawnMg value -2
setoption name BackwardPawnEg value -1
setoption name BackwardOnOpenMg value -10
;
; PATTERNS
;
setoption name FianchBase value 8 ; standard : 13
setoption name FianchKing value 10 ; standard : 20
setoption name ReturningB value 5 ; standard : 10
;
; AUTRES PARAMÈTRES
;
setoption name Contempt value 25 ; joue pour le gain
setoption name SlowMover value 100
setoption name Selectivity value 175
setoption name SearchSkill value 10
setoption name BookFilter value 20
;
; BIBLIOTHÈQUES
;
setoption name GuideBookFile value players/ph-larsen2.bin
setoption name MainBookFile value hist/_31to80.bin
;
; RB 221118 : found in orig larsen.txt
;
; setoption name blockedcpawn value -17

```

**Comment by eduherminio** [comment]
Very interesting to see such a different behavior from different personalities of the same engine!
It's true that with so many parameters, countless different 'personalities' can be created, but choosing something that makes sense seems like a piece of art to me!

**Comment by tissatussa** [comment]
The Rodent project seems to have stopped, last version is IV (4). The author is content with the result, he wrote a nice "Final Rodent" document, which you can find here : https://github.com/nescitus/rodent-iv/blob/master/docs/FinalRodent.pdf .. it also shows a simple web form to create any personality .. Rodent versions II and III have different personality file formats, and some people tried to adjust existing personality parameters into the IV version, eg. Rob Robinson, he wrote a nice article about it : http://echecs-et-informatique.franceserv.com/personnalites-pour-rodent-iv.html .. it's in French, but you can easily do a Google Translate to read it in English (or any other language). It describes the style of many great grandmasters and the way this is reflected by parameters.

> choosing something that makes sense seems like a piece of art to me!

indeed, i also wonder how this was done and tested .. at first this GitHub Issue is about "parameter tuning with test positions" and i took the concerning position as an example, because it has an "unexpected" solution : Ng4 !? By using Multi-PV in SCID we see how this move is judged by different engines. I think MPV is nice, i use it a lot, but Lynx does not have it .. i can advise you to create it, because MPV often can show that many moves are having almost the same eval value, but finally one of them is "best move" !? I guess inside any engine such parameters exist, and they are tuned by the programmer, not by a personality file .. why does Lynx not find Ng4 ? Or is this move close to being "best move" and we don't know because of MPV=1 ?

**Comment by eduherminio** [comment]
True, Multi-PV seems to be a useful feature for tuning purposes in order to understand how far the engine is from considering certain line as the preferred one, I'll try to get that implemented soon!

**Comment by tissatussa** [comment]
> I'll try to get that implemented soon!

nice ! Some time ago I also discussed this with the author of the Weiss chess engine, and he implemented it. Here you can take my advise : in SCID we can see all MPV moves and their order changing during evaluation and rising depth .. some engines constantly update the SCID MPV list while calculating, but not all engines output their move lines in a proper way so SCID understands the (changed) order .. this is very annoying : a move down the list may have a higher eval .. other engines (like Weiss) only output the complete MPV move list when all moves of the concerning depth have been processed. This is simple and works best.

**Comment by tissatussa** [comment]
recently i'm working on a terminal script to display some graph of the MultiPV evaluations while calculating a position upto a certain depth : i give a time limit to the (UCI) engine engine .. not all engines have the UCI protocol properly implemented and i'm still working on the script, but here's a short screencast .. it's about this FEN position :

`r2q1rk1/1p3pb1/p2pb1p1/3Np2p/2PnP3/4N2P/PP2BPPK/R2Q1R2 b - - 0 17`

![Freddie-Attack-Black-to-move](https://user-images.githubusercontent.com/1109281/205931529-6cacf56f-d132-4cae-8469-22b7917ec133.png)

Kalashnikow (Sicilian)
The Freddie Attack | NN vs Kevin Glosser
https://www.youtube.com/watch?v=VRcEf5LvCao&ab_channel=PowerPlayChess

in the game Black played ...f5 !?

https://user-images.githubusercontent.com/1109281/205931568-9fcb0db3-0e7f-4368-b694-f6036bb5d0b7.mp4

eg. `26:1` means : at the concerning depth the move has/had cp 26 at mpv 1

**Comment by eduherminio** [comment]
That script is looking great!

**Comment by tissatussa** [comment]
last few days i worked a bit on a better version of that script .. this position is a good example :

![mpvGraph_Arasan_g2g4](https://user-images.githubusercontent.com/1109281/206885474-75fd0337-c7cb-449f-aaab-731b614d9644.png)


when Arasan evalatuates it at MultiPV 20 (!), we see how the final best move rises in value : watch g2g4, which is the solution of this 'puzzle' - from a real game though .. at depth 13,14,15 the move appears first (orange:1) but later other moves are 'best' .. at the very end indeed g2g4 appears 'best move' and two extra depth columns (20 and 21) are shown when the engine stops - this is because the depth info output is always two columns behind the input, eg. in the UCI info lines which i filter, when depth 18 first appears, the cp:mpv data of all moves on depth 16 (2 behind) are displayed, while no other depth 16 data will ever come - this is my experience while filtering the info line data of several different engines .. it must be the UCI protocol or the they have implemented MultiPV, i have no clue how to code such ..

video : MultiPV score change reaching higher depth 
the total / per depth durations are displayed at each depth. 
and there's some music, while watching 

_J. Polgar-Berkes, Budapest Hunguest Hotels 2003_
`r1bq1r1k/p1pnbpp1/1p2p3/6p1/3PB3/5N2/PPPQ1PPP/2KR3R w - - 0 1`

https://user-images.githubusercontent.com/1109281/206885530-464ffcd3-1895-43d1-b394-973a30a9a127.mp4

**Comment by eduherminio** [comment]
Quick update on this, multi-PV didn't make it to V1.0.0, but I'm planning to add it in the near-mid future
